default: &default
  adapter: mysql2
  encoding: utf8
  username: caio
  password: R@ichu3004
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: scon2

test:
  <<: *default
  database: scon2

production:
  <<: *default
  database: scon2